### ISSUE TITLE
Integration test for the Metrics system

### ISSUE THREAD

**Issue by vthakur7f** [ukama/ukama#466]
- [x] Dokcer Compos file
- [x] Rest examples

**Comment by vthakur7f** [comment]
Metrics Postmant API spec:
```
{
	"info": {
		"_postman_id": "7a34c933-f686-4017-96c7-e950e6660112",
		"name": "Metrics",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "16761762"
	},
	"item": [
		{
			"name": "MetricsGateway",
			"item": [
				{
					"name": "Ping",
					"request": {
						"method": "GET",
						"header": [],
						"url": {
							"raw": "{{METRICS_API}}/ping",
							"host": [
								"{{METRICS_API}}"
							],
							"path": [
								"ping"
							]
						}
					},
					"response": [
						{
							"name": "Ping",
							"originalRequest": {
								"method": "GET",
								"header": [],
								"url": {
									"raw": "{{METRICS_API}}/ping",
									"host": [
										"{{METRICS_API}}"
									],
									"path": [
										"ping"
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "json",
							"header": [
								{
									"key": "Content-Type",
									"value": "application/json; charset=utf-8"
								},
								{
									"key": "Date",
									"value": "Mon, 27 Mar 2023 20:39:37 GMT"
								},
								{
									"key": "Content-Length",
									"value": "43"
								}
							],
							"cookie": [],
							"body": "{\n    \"message\": \"pong\",\n    \"service\": \"metrics@0.0.\"\n}"
						}
					]
				},
				{
					"name": "Metrics",
					"request": {
						"method": "GET",
						"header": [],
						"url": {
							"raw": "{{METRICS_API}}/v1/metrics",
							"host": [
								"{{METRICS_API}}"
							],
							"path": [
								"v1",
								"metrics"
							]
						}
					},
					"response": [
						{
							"name": "Metrics",
							"originalRequest": {
								"method": "GET",
								"header": [],
								"url": {
									"raw": "{{METRICS_API}}/v1/metrics",
									"host": [
										"{{METRICS_API}}"
									],
									"path": [
										"v1",
										"metrics"
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "json",
							"header": [
								{
									"key": "Content-Type",
									"value": "application/json; charset=utf-8"
								},
								{
									"key": "Date",
									"value": "Tue, 28 Mar 2023 23:15:31 GMT"
								},
								{
									"key": "Content-Length",
									"value": "234"
								}
							],
							"cookie": [],
							"body": "[\n    \"cpu\",\n    \"users\",\n    \"inactive_users\",\n    \"inactive_members\",\n    \"sim_usage_duration\",\n    \"inactive_orgs\",\n    \"active_members\",\n    \"memory\",\n    \"inactive_sims\",\n    \"sites\",\n    \"sim_usage\",\n    \"sim_count\",\n    \"active_sims\",\n    \"terminated_sims\",\n    \"active_users\",\n    \"active_orgs\",\n    \"networks\"\n]"
						}
					]
				},
				{
					"name": "OrgsBasedApi",
					"request": {
						"method": "GET",
						"header": [],
						"url": {
							"raw": "{{METRICS_API}}/v1/orgs/:org/metrics/:metric_name",
							"host": [
								"{{METRICS_API}}"
							],
							"path": [
								"v1",
								"orgs",
								":org",
								"metrics",
								":metric_name"
							],
							"variable": [
								{
									"key": "org",
									"value": "556e8c98-2ee8-4c62-8770-5f967f842a3f"
								},
								{
									"key": "metric_name",
									"value": "networks"
								}
							]
						}
					},
					"response": [
						{
							"name": "OrgsSiteSum",
							"originalRequest": {
								"method": "GET",
								"header": [],
								"url": {
									"raw": "{{METRICS_API}}/v1/orgs/:org/metrics/:metric_name",
									"host": [
										"{{METRICS_API}}"
									],
									"path": [
										"v1",
										"orgs",
										":org",
										"metrics",
										":metric_name"
									],
									"variable": [
										{
											"key": "org",
											"value": "a83fe83d-4680-4d97-bbba-c949181a6d38"
										},
										{
											"key": "metric_name",
											"value": "sites"
										}
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "plain",
							"header": [
								{
									"key": "Date",
									"value": "Tue, 28 Mar 2023 21:55:47 GMT"
								},
								{
									"key": "Content-Length",
									"value": "162"
								},
								{
									"key": "Content-Type",
									"value": "text/plain; charset=utf-8"
								}
							],
							"cookie": [],
							"body": "{\"status\":\"success\",\"data\":{\"resultType\":\"vector\",\"result\":[{\"metric\":{\"env\":\"dev\",\"org\":\"a83fe83d-4680-4d97-bbba-c949181a6d38\"},\"value\":[1680040547.105,\"10\"]}]}}"
						},
						{
							"name": "OrgsNetwork",
							"originalRequest": {
								"method": "GET",
								"header": [],
								"url": {
									"raw": "{{METRICS_API}}/v1/orgs/:org/metrics/:metric_name",
									"host": [
										"{{METRICS_API}}"
									],
									"path": [
										"v1",
										"orgs",
										":org",
										"metrics",
										":metric_name"
									],
									"variable": [
										{
											"key": "org",
											"value": "a83fe83d-4680-4d97-bbba-c949181a6d38"
										},
										{
											"key": "metric_name",
											"value": "networks"
										}
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "plain",
							"header": [
								{
									"key": "Date",
									"value": "Tue, 28 Mar 2023 23:17:56 GMT"
								},
								{
									"key": "Content-Length",
									"value": "161"
								},
								{
									"key": "Content-Type",
									"value": "text/plain; charset=utf-8"
								}
							],
							"cookie": [],
							"body": "{\"status\":\"success\",\"data\":{\"resultType\":\"vector\",\"result\":[{\"metric\":{\"env\":\"dev\",\"org\":\"a83fe83d-4680-4d97-bbba-c949181a6d38\"},\"value\":[1680045476.751,\"3\"]}]}}"
						},
						{
							"name": "OrgsActiveMembers",
							"originalRequest": {
								"method": "GET",
								"header": [],
								"url": {
									"raw": "{{METRICS_API}}/v1/orgs/:org/metrics/:metric_name",
									"host": [
										"{{METRICS_API}}"
									],
									"path": [
										"v1",
										"orgs",
										":org",
										"metrics",
										":metric_name"
									],
									"variable": [
										{
											"key": "org",
											"value": "a83fe83d-4680-4d97-bbba-c949181a6d38"
										},
										{
											"key": "metric_name",
											"value": "active_members"
										}
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "plain",
							"header": [
								{
									"key": "Date",
									"value": "Tue, 28 Mar 2023 23:18:44 GMT"
								},
								{
									"key": "Content-Length",
									"value": "178"
								},
								{
									"key": "Content-Type",
									"value": "text/plain; charset=utf-8"
								}
							],
							"cookie": [],
							"body": "{\"status\":\"success\",\"data\":{\"resultType\":\"vector\",\"result\":[{\"metric\":{\"env\":\"dev\",\"org\":\"a83fe83d-4680-4d97-bbba-c949181a6d38\",\"state\":\"active\"},\"value\":[1680045524.188,\"2\"]}]}}"
						}
					]
				},
				{
					"name": "NetworkBasedAPI",
					"request": {
						"method": "GET",
						"header": [],
						"url": {
							"raw": "{{METRICS_API}}/v1/networks/:network/metrics/:metric_name",
							"host": [
								"{{METRICS_API}}"
							],
							"path": [
								"v1",
								"networks",
								":network",
								"metrics",
								":metric_name"
							],
							"variable": [
								{
									"key": "network",
									"value": "9813f208-0525-4b46-b998-5848dc75dd6e"
								},
								{
									"key": "metric_name",
									"value": "sites"
								}
							]
						}
					},
					"response": [
						{
							"name": "Sites",
							"originalRequest": {
								"method": "GET",
								"header": [],
								"url": {
									"raw": "{{METRICS_API}}/v1/networks/:network/metrics/:metric_name",
									"host": [
										"{{METRICS_API}}"
									],
									"path": [
										"v1",
										"networks",
										":network",
										"metrics",
										":metric_name"
									],
									"variable": [
										{
											"key": "network",
											"value": "9813f208-0525-4b46-b998-5848dc75dd6e"
										},
										{
											"key": "metric_name",
											"value": "sites"
										}
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "plain",
							"header": [
								{
									"key": "Date",
									"value": "Tue, 28 Mar 2023 21:58:08 GMT"
								},
								{
									"key": "Content-Length",
									"value": "210"
								},
								{
									"key": "Content-Type",
									"value": "text/plain; charset=utf-8"
								}
							],
							"cookie": [],
							"body": "{\"status\":\"success\",\"data\":{\"resultType\":\"vector\",\"result\":[{\"metric\":{\"env\":\"dev\",\"network\":\"9813f208-0525-4b46-b998-5848dc75dd6e\",\"org\":\"a83fe83d-4680-4d97-bbba-c949181a6d38\"},\"value\":[1680040688.362,\"6\"]}]}}"
						}
					]
				},
				{
					"name": "Metrics",
					"request": {
						"method": "GET",
						"header": [],
						"url": {
							"raw": "{{METRICS_API}}/v1/metrics/:metric_name",
							"host": [
								"{{METRICS_API}}"
							],
							"path": [
								"v1",
								"metrics",
								":metric_name"
							],
							"variable": [
								{
									"key": "metric_name",
									"value": "active_orgs"
								}
							]
						}
					},
					"response": [
						{
							"name": "ActiveOrgs",
							"originalRequest": {
								"method": "GET",
								"header": [],
								"url": {
									"raw": "{{METRICS_API}}/v1/metrics/:metric_name",
									"host": [
										"{{METRICS_API}}"
									],
									"path": [
										"v1",
										"metrics",
										":metric_name"
									],
									"variable": [
										{
											"key": "metric_name",
											"value": "active_orgs"
										}
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "plain",
							"header": [
								{
									"key": "Date",
									"value": "Tue, 28 Mar 2023 21:58:36 GMT"
								},
								{
									"key": "Content-Length",
									"value": "133"
								},
								{
									"key": "Content-Type",
									"value": "text/plain; charset=utf-8"
								}
							],
							"cookie": [],
							"body": "{\"status\":\"success\",\"data\":{\"resultType\":\"vector\",\"result\":[{\"metric\":{\"env\":\"dev\",\"state\":\"active\"},\"value\":[1680040716.336,\"2\"]}]}}"
						},
						{
							"name": "ActiveUsers",
							"originalRequest": {
								"method": "GET",
								"header": [],
								"url": {
									"raw": "{{METRICS_API}}/v1/metrics/:metric_name",
									"host": [
										"{{METRICS_API}}"
									],
									"path": [
										"v1",
										"metrics",
										":metric_name"
									],
									"variable": [
										{
											"key": "metric_name",
											"value": "active_users"
										}
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "plain",
							"header": [
								{
									"key": "Date",
									"value": "Tue, 28 Mar 2023 21:59:33 GMT"
								},
								{
									"key": "Content-Length",
									"value": "149"
								},
								{
									"key": "Content-Type",
									"value": "text/plain; charset=utf-8"
								}
							],
							"cookie": [],
							"body": "{\"status\":\"success\",\"data\":{\"resultType\":\"vector\",\"result\":[{\"metric\":{\"env\":\"dev\",\"service\":\"org\",\"state\":\"active\"},\"value\":[1680040773.318,\"2\"]}]}}"
						}
					]
				},
				{
					"name": "SubscriberUsage",
					"request": {
						"method": "GET",
						"header": []
					},
					"response": [
						{
							"name": "SubscriberUsage",
							"originalRequest": {
								"method": "GET",
								"header": [],
								"url": {
									"raw": "{{METRICS_API}}/v1/subscriber/:subscriber/orgs/:org/networks/:network/metrics/:metric?from=1680042340&step=10&to",
									"host": [
										"{{METRICS_API}}"
									],
									"path": [
										"v1",
										"subscriber",
										":subscriber",
										"orgs",
										":org",
										"networks",
										":network",
										"metrics",
										":metric"
									],
									"query": [
										{
											"key": "from",
											"value": "1680042340"
										},
										{
											"key": "step",
											"value": "10"
										},
										{
											"key": "to",
											"value": null
										}
									],
									"variable": [
										{
											"key": "subscriber",
											"value": "c214f255-0ed6-4aa1-93e7-e333658c7318"
										},
										{
											"key": "org",
											"value": "75ec112a-8745-49f9-ab64-1a37edade794"
										},
										{
											"key": "network",
											"value": "9fd07299-2826-4f8b-aea9-69da56440bec"
										},
										{
											"key": "metric",
											"value": "sim_usage"
										}
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "plain",
							"header": [
								{
									"key": "Date",
									"value": "Tue, 28 Mar 2023 22:27:56 GMT"
								},
								{
									"key": "Content-Length",
									"value": "609"
								},
								{
									"key": "Content-Type",
									"value": "text/plain; charset=utf-8"
								}
							],
							"cookie": [],
							"body": "{\"status\":\"success\",\"data\":{\"resultType\":\"matrix\",\"result\":[{\"metric\":{\"env\":\"dev\",\"name\":\"usage\",\"network\":\"9fd07299-2826-4f8b-aea9-69da56440bec\",\"org\":\"75ec112a-8745-49f9-ab64-1a37edade794\",\"sim\":\"b20c61f1-1c5a-4559-bfff-cd00f746697d\",\"sim_type\":\"test_simple\",\"subscriber\":\"c214f255-0ed6-4aa1-93e7-e333658c7318\"},\"values\":[[1680042340,\"4460\"],[1680042350,\"4470\"],[1680042360,\"4470\"],[1680042370,\"4470\"],[1680042380,\"4480\"],[1680042390,\"4480\"],[1680042400,\"4480\"],[1680042410,\"4490\"],[1680042420,\"4490\"],[1680042430,\"4490\"],[1680042440,\"4500\"],[1680042450,\"4500\"],[1680042460,\"4500\"],[1680042470,\"4510\"]]}]}}"
						}
					]
				}
			],
			"description": "Metrics System API's"
		}
	]
}
```

**Comment by vthakur7f** [comment]
Docker Compose:
```
version: "3.9"
services:

  prometheus:
    image: prom/prometheus:latest
    ports:
        - 9090:9090
    volumes:
        - ./prometheus:/etc/prometheus
        - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - ukama-net

  exporter:
    build:
      context: ./exporter
      dockerfile: ./Dockerfile
    ports:
      - "10251:10251"
    environment:
      - DEBUGMODE=true
      - DB_HOST=postgresd
      - DB_PASSWORD=Pass2020!
      - DB_USER=postgres
      - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
      - MSGCLIENT_HOST=msgclient:9095
      - EXPORTER_SERVICE_HOST=exporter
      - EXPORTER_SERVICE_PORT=9092
    restart: always
    networks:
      - ukama-net


  metricsgateway:
    build: 
      context: ./api-gateway
      dockerfile: ./Dockerfile
    ports:
      - "8082:8080"
    environment:
      - METRICSCONFIG_METRICSSERVER=http://prometheus:9090
    restart: always
    depends_on:
      - exporter
    networks:
      - ukama-net

  msgclient:
    build: 
      context: ../messaging/msgClient
      dockerfile: ./Dockerfile
    ports:
      - "9095:9095"
    environment:
      - DEBUGMODE=true
      - DB_HOST=postgresd
      - DB_PASSWORD=Pass2020!
      - DB_USER=postgres
      - QUEUE_URI=amqp://guest:guest@${LOCAL_HOST_IP}:5672
      - SYSTEM=metrics
    restart: always
    depends_on:
      - prometheus
    networks:
      - ukama-net
  
  pushgateway:
    image: prom/pushgateway
    restart: unless-stopped
    ports:
      - "9091:9091"
    networks:
      - ukama-net

volumes:
  postgress-data:
  prometheus-data:

networks:
  ukama-net:
    external: true
    name: services_dev-net

```
